Create TRACEFILE_Gen_ALU.py
Works almost well. The defects are for some overflow cases which are enlisted below:
ERROR: line 62
ERROR: line 74
ERROR: line 92
ERROR: line 110
ERROR: line 158
ERROR: line 218
ERROR: line 230
ERROR: line 236
ERROR: line 296
ERROR: line 386
ERROR: line 434
ERROR: line 500
ERROR: line 608
ERROR: line 620
ERROR: line 632
ERROR: line 764
ERROR: line 806
ERROR: line 926
ERROR: line 962
ERROR: line 1004
ERROR: line 1046
ERROR: line 1124
ERROR: line 1142